CREATE TABLE person
(
    person_id  INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(16) NOT NULL,
    last_name  VARCHAR2(16) NOT NULL,
    birth_date DATE         NOT NULL
);

CREATE TABLE employee_type
(
    employee_type_id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title            VARCHAR2(64) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY
);

CREATE TABLE location
(
    location_id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    street      VARCHAR2(128) NOT NULL,
    city        VARCHAR2(48),
    state       CHAR(2),
    phone       CHAR(10),
    square_feet NUMBER,
    room_count  NUMBER
);

CREATE TABLE employee
(
    person_id        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ssn              CHAR(9) NULL,
    start_date       DATE    NULL,
    termination_date DATE    NULL,
    employee_type_id NUMBER  NOT NULL REFERENCES employee_type (employee_type_id),
    location_id      NUMBER  NOT NULL REFERENCES location (location_id),
    manager_id       NUMBER  NOT NULL REFERENCES employee (person_id)
);
